### ISSUE TITLE
Wiki or Documentation?

### ISSUE THREAD

**Issue by Frustrated-Programmer** [xatupal/KeeTheme#17]
So I've noticed the Wiki is empty and redirects me to the root of KeeTheme, I don't know if it's possible for Users to create Pull Requests to the Wiki otherwise I would have already.

I created a sample of what I'd expect the documentation _could_ look like. I'm offering to create the bulk of the Documentation (for free) with your permission. Unless you already have plans or other feelings on this matter. Theres still lots of items in the sample that I can't figure out what they do. For example: 

    [Button]
    BackColor = #F00
    ForeColor = #00F

 seems todo absolutely nothing.

I created a sample that you can view the files here: [uploaded to mediafire.](http://www.mediafire.com/folder/yoc7ydy3yf9cu/Documentation)
And I made a PDF version of it so you wouldn't have to download anything if you don't want to.
[Instructions.markdown.pdf](https://github.com/xatupal/KeeTheme/files/3623442/Instructions.markdown.pdf) (Uploaded to github)

**Comment by xatupal** [comment]
Thanks for the sample. I like it. You're welcome to create the documentation. If you have any questions do not hesitate to ask. Tip: @BradyThe described many of the menu items in his [DarkenKP](https://github.com/BradyThe/DarkenKP/blob/master/KeeTheme.ini) theme.

Unfortunately GitHub doesn't support pull requests for the wiki repository, but you can send it directly to me and I will put it on the wiki page.

As for `[Button]` - you've found a bug. I didn't notice it because in my theme control colors are the same as button colors. I will fix it.

**Comment by Frustrated-Programmer** [comment]
Sorry it's been so long! The completed documentation is located https://www.mediafire.com/folder/tiats2w2kn87c/
I have a list of items that don't work [Broken.txt](https://github.com/xatupal/KeeTheme/files/3688435/Broken.txt) and/or I can't find out where they are used in.

**Comment by xatupal** [comment]
Thank you! Well done! I've published your documentation.
I need to check those things that don't work and fix them.
