### ISSUE TITLE
KeeTheme visual not applied to KeeAgent tab

### ISSUE THREAD

**Issue by pvlmkvn** [xatupal/KeeTheme#24]
Hi,

I just started using KeeAgent and the KeeTheme is not applied to its tab. Could you check if this might be perhaps possible - either by tweaking KeeTheme or if you can point out what might KeeAgent do differently?

Thanks for the great plugin!
![KeePass_PL7tcRJSsE](https://user-images.githubusercontent.com/29632121/73353238-37157400-4293-11ea-852c-fa90f595030f.png)
![KeePass_Llxg6A5ca0](https://user-images.githubusercontent.com/29632121/73353243-38df3780-4293-11ea-9450-9f2b8d532205.png)

**Comment by xatupal** [comment]
Hi! I've checked KeeAgent source code. The reason why that tab is not themed is because it is added after the form was shown. Whereas theme is applied after the form is created (it is invisible then) and before it is shown - so you don't see flickering. I can try to handle it but I can't guarantee success.

**Comment by pvlmkvn** [comment]
Hi Krzysztof,

Thanks for taking a look at this, appreciate your time.

-pavel
