### ISSUE TITLE
Doesn't (always?) "Auto-sync with Windows 10 theme"

### ISSUE THREAD

**Issue by nurbles** [xatupal/KeeTheme#90]
I've disabled as much theming as I could to use the bare minimum or a static wallpaper and whatever colors the system selected.  Then I activated Dark Mode.

KeeTheme does NOT automatically switch between Dark Mode and Light Mode when I change the setting in Windows.  I've tried both the System and Applications settings separately, but this is a purely _manual_ setting within KeePass/KeeTheme.

Is it possible for KeeTheme to listen for a WM_WININICHANGE broadcast with lParam == "ImmersiveColorSet" and then check the appropriate registry setting to sett the current LightMode setting?  Those can be found in the registry at
```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\SystemUseLightTheme

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme
```
If so, then it would be automatically following the system theme for light/dark mode.

**Comment by xatupal** [comment]
Hi! Unfortunately, I couldn't reproduce the problem. KeeTheme uses `SystemEvents.UserPreferenceChanged` to detect color mode changes. I've checked the implementation of this event and it turned out that under the hood it uses `WM_WININICHANGE`.

Do you have any other plugins installed? Maybe something else is causing the problem.

**Comment by xatupal** [comment]
No problem. Enjoy the plugin! :)
